import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/navbar/shared/Footer";
import { CartProvider } from "@/components/navbar/shared/CartContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ThemeProvider } from "@/context/themeConext";
import "./globals.css";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce made",
  description: "Generated by create E-commerce made",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body className={`${rubik.variable} h-full antialiased`}>
    <ThemeProvider>
      <CartProvider>
        <Navbar />
        <main className="min-h-screen max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </main>
        <ToastContainer position="top-right" autoClose={2000}/>
        <footer>
          <Footer />
        </footer>
      </CartProvider>
    </ThemeProvider>
  </body>
</html>

  );
}
